config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'

  resources :posts do
    resources :comments
  end

  root 'posts#index'
  get '/arturo' => 'posts#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	validates_presence_of :title
	validates_presence_of :body
	validates_length_of :body, :in => 10..400, :message => "La longitud no es valida"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        flash[:success] = "Se guardó correctamente el post"
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        flash[:alert] = "No pudo ser guardado el post"
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<section class="row" style="margin: -10px;">
  
<div class="small-4 columns">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit 'Aceptar', :class => 'button small round success' %>
    </div>
  </div>
</section>
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1 style="color:white; padding-left:10px">MY APP</h1>
		</li>
	</ul>
	<section class="top-bar-section">
		<ul class="left">
			<li class="has-dropdown not-click"><a href="#">Posts</a>
				<ul class="dropdown">
					<li class="parent-link show-for-small-only"><a class="parent-link js-generated" href="#">DAC-RG-01</a></li>
					<li><label>Post</label></li>
					<% if admin_signed_in? %>
					<li><%= link_to 'Ver', controller: '/posts',action: 'index' %></li>
					<% else %>
					<li><%= link_to 'Ver', controller: '/posts',action: 'index' %></li>
					<li><%= link_to 'Nuevo', controller: '/posts',action: 'new' %></li>
					<% end %>
				</ul>
			</li>
			<li class="divider"></li>
		</ul>

		<ul class="right">
			
		<li class="has-dropdown" id="white">
        <% if user_signed_in? %>
        Entraste como <strong><%= current_user.email %></strong>
        <ul class="dropdown">
        <li><%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to 'Salir', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>     
        </ul>      
        <% end %>

        <% if admin_signed_in? %>
        Entraste como <strong><%= current_admin.email %></strong>
        <ul class="dropdown">
        <li><%= link_to 'Editar Perfil', edit_admin_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to 'Salir', destroy_admin_session_path, method: :delete, :class => 'navbar-link' %></li>     
        </ul>      
        <% end %>



        <% if !admin_signed_in? && !user_signed_in? %>
        No has ingresado
        <ul class="dropdown">
        <li><%= link_to 'Registrate', new_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to 'Ingresa', new_user_session_path, :class => 'navbar-link' %></li>
        </ul>      
        <% end %>

      </li>

		</ul>

	</section>
</nav>

app/views/posts/edit.html.erb
<h1>Editar Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Recientes</h1>

<table>
  <thead>
    <tr>
  <% if user_signed_in? %>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
  <% end %>

  <% if admin_signed_in? %>
      <th>ID</th>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
  <% end %>
      
    </tr>
  </thead>

  <tbody>


  <% if user_signed_in? %>
    <% @posts.each do |post| %>
    <% if post.user_id == current_user.id %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <% if post.body %>
            <a href="#" data-reveal-id="post-<%= post.id %>">Ver más</a>
            <div id="post-<%= post.id %>" class="reveal-modal" data-reveal>
              <%= post.body %>
              <a class="close-reveal-modal">&#215</a>
            </div>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Borrar', post, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    <% end %>
    <% end %>




    <% if admin_signed_in? %>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.title %></td>
        <td>
          <% if post.body %>
            <a href="#" data-reveal-id="post-<%= post.id %>">Ver más</a>
            <div id="post-<%= post.id %>" class="reveal-modal" data-reveal>
              <%= post.body %>
              <a class="close-reveal-modal">&#215</a>
            </div>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Borrar', post, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
    <% end %>


  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'Crear nuevo post', new_post_path %>
<% end %>

<% if admin_signed_in? %>
 <p>Bienvenido Administrador</p>
<% end %>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>


<div id="comments">
	<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post,Comment.new], remote: true) do |f| %>
	<p> <%= f.label :body, "Nuevo Comentario" %> </br>
		<%= f.text_area :body %>
	</p>
	<p><%= f.submit "Agregar Comentario", :class => 'button small round success' %></p>
	<% end %>